{{- if .Values.storageClass.create }}
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name:  {{ .Values.storageClass.name }}
  labels:
    {{- include "sourcegraph.labels" . | nindent 4 }}
    deploy: sourcegraph-storage
provisioner: {{ .Values.storageClass.provisioner }}
parameters:
  type: {{ .Values.storageClass.type }}
{{- end -}}
